bus:
    device: can0 # socketcan network
    # loopback: false # socket should loop back messages
    # driver_plugin: can::SocketCANInterface
    # master_allocator: canopen::SimpleMaster::Allocator
sync:
    interval_ms: 1000 # set to 0 to disable sync
    #update_ms: 100 #update interval of control loop, must be set explecitly if sync is disabled
    overflow: 0 # overflow sync counter at value or do not set it (0, default)
#heartbeat: # simple heartbeat producer, optional!
#  rate: 20 # heartbeat rate
#  msg: "77f#05" # message to send, cansend format: heartbeat of node 127 with status 5=Started
