# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 125

# Settings for ros_control hardware interface
#hardware_interface:
#   joints:
#     - left_rope_motor

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 125

# velocity Controller
left_rope_vel_controller:
  type: 'velocity_controllers/JointVelocityController'
  joint: 'left_rope_motor'
  required_drive_mode: 2
