# struct syntax
nodes:
    left_rope_motor:
        id: 1
        eds_pkg: rr_yukon_drive # optionals package  name for relative path
        eds_file: "config/YukonDrive-1021-ADO_V4.15-31.EDS" # path to EDS/DCF file
